### ISSUE TITLE
Reward for party members? E. g. reward for non-standard characters

### ISSUE THREAD

**Issue by rubyFeedback** [RamosPabloA/NPC_Dusk_MOD#73]
Hey there Ramos and everyone else,

I'll soon start a new run in 2024. Dusk is my favourite NPC or rather the whole mod, despite
the small bugs or issues.

One thing that I have noticed in the past, but I am not sure ... if you defeat the guy in the
troll mound, you get an item. A chest or so that is heavy and can not be dropped.

First, I somehow managed to pick it up again (don't ask me how ...) and then I could not
get rid of it anymore. Korgan was carrying it. Actually not sure how I ended up with 
twice of it. I also already got the reward, so I must have delivered it back to the
leprechaun. Not sure if you want to fix such a very rare thing (I even forgot HOW I
picked it up, but in prior installations I could somehow clone all enemies and allies
so perhaps there is a missing check). Perhaps a small routine could be added such
as:

"if chest is in inventory AND the reward for completing that part of the quest has
been given already, then simply remove the chest again if it is still in the inventory".

Not sure how to do such a check in the DSL, but I assume the code for this must
already exist, as the chest is removed correctly after the reward.

Anyway, this is an aside. I wanted to talk about the rewards. Not about the power,
because I think the rewards are a bit too powerful, but don't take them away! :D

Although perhaps the vorpal axe should be changed a bit; in particular vorpal
nuking strong enemies seems a bit powerful. Perhaps that could be slightly
decreased or so, or another ability be given but vorpal removed (Korgan is just
too deadly with it, I give him the vorpal axe and the strength 25 hammer, the
guy is a powergod).

When I had a different party composition, it seems as if some party members
did not get any reward. I assume you give some specific reward to individual
NPCs but not to others? Perhaps I am wrong. But, if this is the case, could it
be made sure that others get a reward too? If I recall correctly in my last 
playthrough, not all NPCs got a reward. In particular I think when I got some
NPC from skitia or some rare non-default class, I think they did not get any
reward. I may be wrong here.

But! If I am right, perhaps there could be a generic reward? I am not sure
about it, has been a few weeks since I last played through.

I'll play through with Dusk MOD v1.5.0 next and then give a bit more feedback.

Please also feel free to close issues I report even if they can not be resolved
because they are too much work.

Tactics remix mod is interesting but also buggy, IMO, so I think issues related
to NPC Dusk are more due to Tactics remix. I actually like the challenge by
Tactics remix, even though I complained (in particular about disabling exits,
to forbid running out, I hate that ... like when I walk up the stairs in that
building where the celestial fury katana is used by one guy, suddenly I can
no longer go downstairs? But I could go upstairs before? It's so weird. 
Anyway thanks for coming up with work arounds there. Some other parts
of Tactics remix are quite cool. Like the acid katana guy. May be interesting
for NPC Dusk to also add a slayer bounty hunter who tries to hunt down
Dusk in Throne of Bhaal or so, but anyway, I don't really want to suggest
more of your time investment. Having someone polish a MOD and maintain
it is already awesome, so many mods are kind of dormant or abandoned.
Last suggestion, it may also be interesting to allow for the MOD itself to
have the main actor be a wizard slayer like Dusk. Perhaps also the rewards
so kind of rather than Dusk, allow the main guy to be a wizard slayer like
Dusk. But that's just an idea. Dusk is super-useful in particular due to the
courage thing that cancels fear effects, that is actually my favourite 
ability of him since it is very convenient. Insta-healing is great too, this
helps the weaker chars. The damage reduction is useful but not as useful
as the other abilities IMO.)

**Comment by RamosPabloA** [comment]
Hi! I'm glad you're enjoying the mod.

-     The duplicated chest/box you pick up from the battle against Alabarza is actually a bug. I have already applied a patch to fix that.
-     I can nerf Korgan's Golden Axe; I need to check that out, so details will be displayed in the upcoming updates.
-     We're already working on a patch that will fix the issue with the Tactics Remix mod. For that, Mathyus and Michelson are going to have another hideout in the Docks (we're going to create a new small area for that).
-     Custom rewards for NPCs are only available for Vanilla characters and EE characters. NPCs from other mods are not applied for that because we don't do crossmods with another NPCs mod yet. That's why we create some kind of neutral reward for that. Gorion's ward can choose between gold, a legendary sword, or a bunch of magical items.
-     Gorion's ward can be a Wizard Slayer and use the Benork's item set (this set is only usable by Wizard Slayers; Dusk can use them too, but Dusk also has his personal items too).
-     We're actually working on a new NPC mod that will crossmod with Dusk's. The plan is to work on this NPC mod first and, after that, a final NPC mod. So we'll have three NPC mods and a huge quest in Throne of Bhaal for these three characters (alongside Gorion's ward and two more companions that the player has). All this will take time, but I hope the second NPC mod will be ready in the next couple of months.

Thanks for your feedback; it's really useful.
